# Generated by Django 3.2.8 on 2021-11-08 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_room_price', models.FloatField()),
                ('restauration_bill', models.FloatField(blank=True)),
                ('bar_bill', models.FloatField(blank=True)),
                ('date_of_payment', models.DateTimeField()),
                ('credit_card_number', models.IntegerField()),
                ('payment_state', models.BooleanField(default=False)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.roomreservation')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('1', 'Massage'), ('2', 'SPA'), ('3', 'Romantic Dinner'), ('4', 'Swimming Pool'), ('5', 'Trip'), ('6', 'Breakfast in bed')], default='1', max_length=30)),
                ('price', models.FloatField(blank=True)),
                ('additional_info', models.CharField(blank=True, max_length=500)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.bill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
