# Generated by Django 3.2.8 on 2021-11-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20211110_1920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
