# Generated by Django 3.2.8 on 2021-11-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20211110_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
