# Generated by Django 3.2.8 on 2021-11-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='reservation',
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='bill',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.bill'),
            preserve_default=False,
        ),
    ]
