# Generated by Django 3.2.8 on 2021-11-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_remove_bill_total_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='bill',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.bill'),
        ),
    ]
