# Generated by Django 3.2.8 on 2021-10-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
