# Generated by Django 3.2.8 on 2021-10-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1', 'Standard single'), ('2', 'Standard 2 beds'), ('3', 'Standard king size bed'), ('4', 'Premium single'), ('5', 'Premium 2 beds'), ('6', 'Premium king size bed')], default='1', max_length=30),
        ),
    ]
